#!/bin/bash

torchrun --nnodes=1 --nproc_per_node=8 --master_port=25001 llava/train/train_mem.py \
    --version llama3 \
    --model_name_or_path ../LLaVA-Meta-Llama-3-8B-Instruct-FT-S2 \
    --data_path /path/to/stage1.json \
    --image_folder /path/to/stage1_images \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --deepspeed ./scripts/zero2.json \
    --gradient_checkpointing True \
    --tune_mm_mlp_adapter True \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava-llama-med-8b-stage1 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 500 \
    --save_total_limit 3 \
    --learning_rate 2e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb