#!/bin/bash
export CUDA_VISIBLE_DEVICES=0,1,2,3,5,6,7
torchrun --nnodes=1 --nproc_per_node=7 --master_port=25001 llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --version v0 \
    --model_name_or_path /data2/yunfei/llava3-med/checkpoints/llava-med-7b-pretrain-ds-mn \
    --data_path ../Data/medical_data/LLaVA-Med-annotation/llava_med_instruct_60k_inline_mention.json \
    --image_folder ../Data/normal_data/llavamed_tune \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 True \
    --output_dir ./checkpoints/llava3-med-stage2 \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 8000 \
    --save_total_limit 3 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
